### ISSUE TITLE
android 8.1下异常

### ISSUE THREAD

**Issue by KangCaijun** [WindySha/AndFixProject#2]
java.lang.NoSuchMethodError: No virtual method get(II)I in class Lcom/wind/cache/andfixproject/WrongMethodClass; or its super classes (declaration of 'com.wind.cache.andfixproject.WrongMethodClass' appears in /data/app/com.wind.cache.andfixproject-AxozT-yATcYdTOssXH-KqQ==/base.apk)
        at com.wind.cache.andfixproject.MainActivity.onCreate(MainActivity.java:20)
        at android.app.Activity.performCreate(Activity.java:7076)
        at android.app.Activity.performCreate(Activity.java:7067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2915)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1633)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6627)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by KangCaijun** [comment]
原理跟阿里的sophix一样，但8.1下无法hook成功
